name: 提交博文
description: 提交高考感想博文
assignees:
  - yzqzss
body:
  - type: input
    id: url
    attributes:
      label: 博文网址
      description: 
      placeholder: ex. https://www.keshankang.org/one-year-after-gaokao/
    validations:
      required: true
  - type: input
    id: province
    attributes:
      label: 省份
      description: 
      placeholder: ex. 福建省、上海市
    validations:
      required: false
